import { fetchJson } from './api';

export interface Viewer3DOptions {
  iframe: HTMLIFrameElement;
  modelSelect: HTMLSelectElement;
  resetButton: HTMLButtonElement;
  statusEl: HTMLElement;
  onPicked: (entityGuid: string) => void;
}

/** Bridges this app's tree/property UI to ifclite's own viewer, which runs
 * as a self-contained app inside an iframe (served by a per-model Node
 * sidecar via Flask's /viewer-proxy/<model>/... reverse proxy — see
 * server/viewer_sidecar_manager.py). There is no mesh/geometry code here:
 * ifclite parses and renders model.ifc (generated by
 * server/exporters/ecs_to_ifc.py) entirely on its own. This class only
 * translates between our GUID-keyed selection state and ifclite's
 * expressId-keyed command protocol (POST .../api/command, SSE .../events),
 * confirmed against the real command payloads in ifclite's bundled viewer. */
export class Viewer3D {
  private opts: Viewer3DOptions;
  private currentModel: string | null = null;
  private eventSource: EventSource | null = null;
  private entityGuidToExpressId = new Map<string, number>();
  private expressIdToEntityGuid = new Map<number, string>();
  private highlightedGuids: string[] = [];

  constructor(opts: Viewer3DOptions) {
    this.opts = opts;
    opts.modelSelect.addEventListener('change', () => {
      const model = opts.modelSelect.value;
      if (model) void this.loadModel(model);
    });
    opts.resetButton.addEventListener('click', () => {
      void this.sendCommand({ action: 'reset' });
    });
  }

  async populateModelList(): Promise<void> {
    const models: string[] = await fetchJson('/api/models');
    const select = this.opts.modelSelect;
    const previous = select.value;
    select.innerHTML = '<option value="">Select a model…</option>';
    models.forEach((name) => {
      const option = document.createElement('option');
      option.value = name;
      option.textContent = name;
      select.appendChild(option);
    });
    if (previous && models.includes(previous)) {
      select.value = previous;
    } else if (models.length === 1) {
      select.value = models[0];
      void this.loadModel(models[0]);
    }
  }

  async loadModel(modelName: string): Promise<void> {
    this.teardown();
    this.currentModel = modelName;
    this.opts.statusEl.textContent = `Loading ${modelName}…`;

    try {
      const expressMap: Record<string, number> = await fetchJson(`/api/models/${encodeURIComponent(modelName)}/expressmap`);
      this.entityGuidToExpressId = new Map(Object.entries(expressMap));
      this.expressIdToEntityGuid = new Map(
        Object.entries(expressMap).map(([guid, id]) => [id, guid])
      );
    } catch (error) {
      this.opts.statusEl.textContent = `Failed to prepare ${modelName}: ${(error as Error).message}`;
      return;
    }

    this.opts.iframe.src = `/viewer-proxy/${encodeURIComponent(modelName)}/`;
    this.opts.statusEl.textContent = `Viewing ${modelName}`;

    this.eventSource = new EventSource(`/viewer-proxy/${encodeURIComponent(modelName)}/events`);
    this.eventSource.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        if (data.action === 'picked' && typeof data.expressId === 'number') {
          const entityGuid = this.expressIdToEntityGuid.get(data.expressId);
          if (entityGuid) this.opts.onPicked(entityGuid);
        }
      } catch {
        // ignore malformed/non-JSON SSE frames (e.g. the initial comment ping)
      }
    };
  }

  private teardown(): void {
    if (this.eventSource) {
      this.eventSource.close();
      this.eventSource = null;
    }
    this.entityGuidToExpressId.clear();
    this.expressIdToEntityGuid.clear();
  }

  private async sendCommand(command: Record<string, unknown>): Promise<void> {
    if (!this.currentModel) return;
    try {
      await fetch(`/viewer-proxy/${encodeURIComponent(this.currentModel)}/api/command`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(command),
      });
    } catch {
      // best-effort; the 3D pane simply won't reflect this command
    }
  }

  private expressIdsFor(entityGuids: string[]): number[] {
    return entityGuids
      .map((guid) => this.entityGuidToExpressId.get(guid))
      .filter((id): id is number => id !== undefined);
  }

  /** Replaces the current highlight (single-selection UI: highlighting is
   * additive in ifclite's protocol, so the previous selection is explicitly
   * reset first). */
  highlightEntities(entityGuids: string[]): void {
    const previousIds = this.expressIdsFor(this.highlightedGuids);
    if (previousIds.length) void this.sendCommand({ action: 'resetColorEntities', ids: previousIds });

    this.highlightedGuids = entityGuids;
    const ids = this.expressIdsFor(entityGuids);
    if (ids.length) void this.sendCommand({ action: 'highlight', ids });
  }

  showEntities(entityGuids: string[]): void {
    const ids = this.expressIdsFor(entityGuids);
    if (!ids.length) return;
    void this.sendCommand({ action: 'showEntities', ids });
  }

  hideEntities(entityGuids: string[]): void {
    const ids = this.expressIdsFor(entityGuids);
    if (!ids.length) return;
    void this.sendCommand({ action: 'hideEntities', ids });
  }

  flyToEntities(entityGuids: string[]): void {
    const ids = this.expressIdsFor(entityGuids);
    if (!ids.length) return;
    void this.sendCommand({ action: 'flyto', ids });
  }
}
