#!/usr/bin/env node
// Thin wrapper around @ifc-lite/viewer-core's server: serves ifclite's own
// self-contained viewer app pointed at one IFC-SPF file (generated by
// server/exporters/ecs_to_ifc.py). Spawned and managed per-model by
// server/viewer_sidecar_manager.py and reached only through Flask's
// /viewer-proxy/<model>/... reverse proxy, never directly by the browser.
import { startViewerServer } from '@ifc-lite/viewer-core';

function arg(name, fallback) {
  const idx = process.argv.indexOf(`--${name}`);
  return idx !== -1 && idx + 1 < process.argv.length ? process.argv[idx + 1] : fallback;
}

const filePath = arg('file', null);
const port = parseInt(arg('port', '0'), 10);
const fileName = arg('name', 'model');

if (!filePath) {
  console.error('serve.mjs: missing required --file <path-to-ifc> argument');
  process.exit(1);
}

startViewerServer({
  filePath,
  fileName,
  port,
  onReady: (readyPort, url) => {
    console.log(`[viewer-sidecar] ${fileName} ready on ${url} (pid ${process.pid})`);
  },
  onError: (err) => {
    console.error('[viewer-sidecar] server error:', err);
    process.exit(1);
  },
}).catch((err) => {
  console.error('[viewer-sidecar] failed to start:', err);
  process.exit(1);
});
